// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nphcolyqvcswmfkpcgdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5waGNvbHlxdmNzd21ma3BjZ2RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTU3MzcsImV4cCI6MjA2MDM5MTczN30.Gdm8Dsc7_bL3dJ6UKojjWc-ZUeh9OFfVwjD4rGnYaQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);